# - Find LEVMAR
#
# http://users.ics.forth.gr/~lourakis/levmar/
# 
# The module defines the following variables:
#  LEVMAR_FOUND - the system has LEVMAR
#  LEVMAR_INCLUDE_DIR - where to find LEVMAR.h
#  LEVMAR_INCLUDE_DIRS - LEVMAR includes
#  LEVMAR_LIBRARY - where to find the LEVMAR library
#  LEVMAR_LIBRARIES - aditional libraries

set(LEVMAR_ROOT_DIR ${LEVMAR_DIR})

# set LEVMAR_INCLUDE_DIR
find_path (LEVMAR_INCLUDE_DIR
  NAMES
    levmar.h
  PATHS
    "${LEVMAR_DIR}/include"
  DOC
    "LEVMAR include directory"
)

# set LEVMAR_INCLUDE_DIRS
set (LEVMAR_INCLUDE_DIRS ${LEVMAR_INCLUDE_DIR})


IF (LEVMAR_INCLUDE_DIR)
  SET(LEVMAR_LIBRARY_DIR "${LEVMAR_INCLUDE_DIR}/../lib")

  FIND_LIBRARY(LEVMAR_CORE_LIBRARY_RELEASE NAMES levmar PATHS ${LEVMAR_LIBRARY_DIR})
  SET(LEVMAR_LIBRARY_RELEASE
    ${LEVMAR_CORE_LIBRARY_RELEASE})

  FIND_LIBRARY(LEVMAR_CORE_LIBRARY_DEBUG NAMES levmard PATHS ${LEVMAR_LIBRARY_DIR})
  SET(LEVMAR_LIBRARY_DEBUG
    ${LEVMAR_CORE_LIBRARY_DEBUG})
ENDIF (LEVMAR_INCLUDE_DIR)

if(LEVMAR_LIBRARY_RELEASE)
  if(LEVMAR_LIBRARY_DEBUG)
    set(LEVMAR_LIBRARIES_ optimized ${LEVMAR_LIBRARY_RELEASE} debug ${LEVMAR_LIBRARY_DEBUG})
  else()
    set(LEVMAR_LIBRARIES_ ${LEVMAR_LIBRARY_RELEASE})
  endif()

  set(LEVMAR_LIBRARIES ${LEVMAR_LIBRARIES_} CACHE FILEPATH "The LEVMAR library")
endif()

IF(LEVMAR_INCLUDE_DIR AND LEVMAR_LIBRARIES)
  SET(LEVMAR_FOUND TRUE)
  MESSAGE(STATUS "Found levmar lib: ${LEVMAR_LIBRARIES}")
ENDIF(LEVMAR_INCLUDE_DIR AND LEVMAR_LIBRARIES)

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args (LEVMAR DEFAULT_MSG LEVMAR_LIBRARIES
  LEVMAR_INCLUDE_DIR
  LEVMAR_INCLUDE_DIRS
  LEVMAR_ROOT_DIR
)


mark_as_advanced (
  LEVMAR_LIBRARIES
  LEVMAR_INCLUDE_DIR
  LEVMAR_INCLUDE_DIRS
  LEVMAR_ROOT_DIR
)
